// Login Actions
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS =  'LOGIN_SUCCESS';
export const AUTH_ERROR = 'LOGIN_ERROR';
export const LOGOUT =  'LOGOUT';
export const CHANGE_ROLE = 'CHANGE_ROLE';
export const GET_PROFILE = 'GET_PROFILE';

// Forgot Password Actions
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';

// Reset Password Actions
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

// Verify profile Actions
export const VERIFY_PROFILE_REQUEST = 'VERIFY_PROFILE_REQUEST';
export const VERIFY_PROFILE_SUCCESS = 'VERIFY_PROFILE_SUCCESS';

// Expert Actions
export const SAVE_EXPERT_STEP_1 = 'SAVE_EXPERT_STEP_1';
export const SAVE_EXPERT_STEP_2 = 'SAVE_EXPERT_STEP_2';
export const EXPERT_STEP_1 = 'EXPERT_STEP_1';
export const EXPERT_STEP_2 = 'EXPERT_STEP_2';
export const EXPERT_STEP_3 = 'EXPERT_STEP_3';

export const SUCCESS_SAVE_EXPERT = 'SUCCES_SAVE_EXPERT';
export const ERROR_SAVE_EXPERT = 'ERROR_SAVE_EXPERT';

// Trips Actions
export const SAVE_TRIP_STEP_1 = 'SAVE_TRIP_STEP_1';
export const SAVE_TRIP_STEP_2 = 'SAVE_TRIP_STEP_2';
export const SAVE_TRIP_STEP_3 = 'SAVE_TRIP_STEP_3';
export const TRIP_STEP_1 = 'TRIP_STEP_1';
export const TRIP_STEP_2 = 'TRIP_STEP_2';
export const TRIP_STEP_3 = 'TRIP_STEP_3';
export const UPDATE_TRIP = 'UPDATE_TRIP';

// Learning Actions
export const SAVE_LEARNING_STEP_1 = 'SAVE_LEARNING_STEP_1';
export const SAVE_LEARNING_STEP_2 = 'SAVE_LEARNING_STEP_2';
export const LEARNING_STEP_1 = 'LEARNING_STEP_1';
export const LEARNING_STEP_2 = 'LEARNING_STEP_2';
export const LEARNING_STEP_3 = 'LEARNING_STEP_3';
export const SUCCESS_CREATE_LEARNING = 'SUCCESS_CREATE_LEARNING';
export const ERROR_CREATE_LEARNING = 'ERROR_CREATE_LEARNING';

export const SUCCESS_CREATE_TRIP = 'SUCCESS_CREATE_TRIP';
export const ERROR_CREATE_TRIP = 'ERROR_CREATE_TRIP';
export const UPDATE_LEARNING = 'UPDATE_LEARNING'

// Enthusiast Actions
export const CREATE_ENTHUSIASTS_PROFILE_REQUEST = 'CREATE_ENTHUSIASTS_PROFILE_REQUEST';
export const CREATE_ENTHUSIASTS_PROFILE_SUCCESS = 'CREATE_ENTHUSIASTS_PROFILE_SUCCESS';

// Auth Model Actions
export const OPEN_AUTH_MODEL = 'OPEN_AUTH_MODEL';
export const CLOSE_AUTH_MODEL = 'CLOSE_AUTH_MODEL';

// Choose Profile Model Actions
export const OPEN_CHOOSE_PROFILE = 'OPEN_CHOOSE_PROFILE';
export const CLOSE_CHOOSE_PROFILE = 'CLOSE_CHOOSE_PROFILE';

// Success Modal
export const OPEN_SUCCESS_MODAL = 'OPEN_SUCCESS_MODAL';
export const CLOSE_SUCCESS_MODAL = 'CLOSE_SUCCESS_MODAL';

export const GO_TO_TAB_REQ = 'GO_TO_TAB_REQ';
export const GO_TO_TAB = 'GO_TO_TAB';

export const EDIT_MODE = 'EDIT_MODE';
export const UPDATE_EXPERT_PROFILE = 'UPDATE_EXPERT_PROFILE';

// Enthu Actions
export const SAVE_ENTHU_STEP_1 = 'SAVE_ENTHU_STEP_1';
export const SAVE_ENTHU_STEP_2 = 'SAVE_ENTHU_STEP_2';
export const ENTHU_STEP_1 = 'ENTHU_STEP_1';
export const ENTHU_STEP_2 = 'ENTHU_STEP_2';
export const ENTHU_STEP_3 = 'ENTHU_STEP_3';

export const SUCCESS_SAVE_ENTHU = 'SUCCES_SAVE_ENTHU';
export const ERROR_SAVE_ENTHU = 'ERROR_SAVE_ENTHU';

export const ENTU_TAB_REQ = 'ENTU_TAB_REQ';
export const ENTHU_TAB = 'ENTHU_TAB';

export const OPEN_UPDATE_MODAL = 'OPEN_UPDATE_MODAL';
export const CLOSE_UPDATE_MODAL = 'CLOSE_UPDATE_MODAL';

export const OPEN_APPROVAL_MODAL = 'OPEN_APPROVAL_MODAL';
export const CLOSE_APPROVAL_MODAL = 'CLOSE_APPROVAL_MODAL';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'

// Album action
export const CREATE_ALBUM = 'CREATE_ALBUM';